### ISSUE TITLE
#777 as the main font color is an accessibility nightmare

### ISSUE THREAD

**Issue by jhermann** [PYCONDE/www#4]
If you have young eyes with 20/20 sight, this might not be obvious, but the incredibly low contrast renders the site essentially unreadable in its unchanged state for many people, including me – so yet another site requiring me to apply Stylish just to use it.

Evidence by real users: https://hugogiraudel.com/2017/07/02/accessibility-feedback/

Please change to at most #333, but ideally black (which isn't black on most monitors anyway).

**Comment by hoffmann** [comment]
done. should be updated in an hour.
